package il.co.ilrd.chatserver;

public enum GlobalChatProtocolKeys {
	REGISTRATION_REQUEST,
	REGISTRATION_ACK,
	REGISTRATION_REFUSE,
	NEW_CLIENT_REGISTRATION,
	MESSAGE,
	BROADCAST_MESSAGE,
	ERROR_MESSAGE,
	REMOVE_REQUEST,
	NUM_OF_KEYS;
}