package il.co.ilrd.server.chatserver;

public enum ChatProtocolKeys {
	REGISTRATION_REQUEST,
	REGISTRATION_ACK,
	REGISTRATION_REFUSE,
	NEW_CLIENT_REGISTRATION,
	MESSAGE,
	BROADCAST_MESSAGE,
	ERROR_MESSAGE,
	REMOVE_REQUEST;
}
